import {
  chromium,
  expect,
  type Request,
  type BrowserContext,
} from "@playwright/test";
import { mkdirSync } from "node:fs";

async function main() {
  if (process.env.TEST_ALLOW_ENROLLMENT !== "1")
    throw new Error(
      "Use a disposable database without passkeys and set TEST_ALLOW_ENROLLMENT=1.",
    );
  const base = process.env.TEST_BASE_URL || "http://localhost:5002";
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  const stranger = await browser.newContext();
  const page = await context.newPage();
  const cdp = await context.newCDPSession(page);
  await cdp.send("WebAuthn.enable");
  const options = {
    protocol: "ctap2" as const,
    transport: "internal" as const,
    hasResidentKey: true,
    hasUserVerification: true,
    isUserVerified: true,
    automaticPresenceSimulation: true,
  };
  const { authenticatorId } = await cdp.send(
    "WebAuthn.addVirtualAuthenticator",
    { options },
  );
  const errors: string[] = [];
  const actions = new Map<string, Request>();
  let staleCookie: Awaited<ReturnType<BrowserContext["cookies"]>>[number];
  let forgeOrigin = false;
  const legacyRequests: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("request", (request) => {
    if (/\/api\/(auth|dashboard|projects|issues)(\/|$|\?)/.test(request.url()))
      legacyRequests.push(request.url());
  });
  async function replay(
    who: BrowserContext,
    request: Request,
    body = request.postData()!,
    origin: string | null = base,
  ) {
    return who.request.post(base + "/login", {
      headers: {
        "next-action": request.headers()["next-action"],
        "content-type": request.headers()["content-type"],
        accept: "text/x-component",
        ...(origin ? { origin } : {}),
      },
      data: body,
    });
  }
  // Capture the actual action requests generated by Next, never hard-code action IDs.
  await page.route("**/*", async (route) => {
    const request = route.request();
    if (!request.headers()["next-action"]) {
      await route.continue();
      return;
    }
    const args = request.postDataJSON();
    if (args[0]?.response?.attestationObject) actions.set("register", request);
    if (args[0]?.response?.signature) {
      actions.set("authenticate", request);
      if (forgeOrigin) {
        const client = JSON.parse(
          Buffer.from(args[0].response.clientDataJSON, "base64url").toString(),
        );
        client.origin = "https://evil.example";
        args[0].response.clientDataJSON = Buffer.from(
          JSON.stringify(client),
        ).toString("base64url");
        await route.continue({ postData: JSON.stringify(args) });
        return;
      }
    }
    const response = await route.fetch();
    const text = await response.text();
    if (text.includes('"rp":')) {
      actions.set("registrationOptions", request);
      if (!staleCookie) {
        const other = await replay(stranger, request);
        expect(await other.text()).toContain('"challenge"');
        staleCookie = (await stranger.cookies()).find(
          (cookie) => cookie.name === "cg_challenge",
        )!;
      }
    }
    if (text.includes('"stats":')) actions.set("dashboard", request);
    if (text.includes('"keys":')) actions.set("keys", request);
    if (
      typeof args[0] === "string" &&
      args.length === 1 &&
      text.includes('"ok":true')
    )
      actions.set("remove", request);
    await route.fulfill({ response });
  });
  try {
    // The first HTML response must contain the final setup screen, without
    // waiting for hydration or an authentication-status request.
    const noJavaScript = await browser.newContext({ javaScriptEnabled: false });
    const firstPaint = await noJavaScript.newPage();
    await firstPaint.goto(base + "/login");
    await expect(
      firstPaint.getByRole("heading", { name: "Set up your passkey" }),
    ).toBeVisible();
    await expect(
      firstPaint.getByLabel("Passkey name", { exact: true }),
    ).toBeVisible();
    await expect(firstPaint.locator(".auth-logo")).toBeVisible();
    await expect(firstPaint.locator(".loading")).toHaveCount(0);
    await noJavaScript.close();
    await page.goto(base + "/?view=projects");
    await expect(page).toHaveURL(/\/login\?next=/);
    await expect(
      page.getByRole("heading", { name: "Set up your passkey" }),
    ).toBeVisible();
    mkdirSync("test-results", { recursive: true });
    await page.screenshot({ path: "test-results/passkey-setup.png" });
    await page.getByLabel("Passkey name", { exact: true }).fill("My laptop");
    await page
      .getByRole("button", { name: "Create passkey", exact: true })
      .click();
    await expect(page).toHaveURL(base + "/?view=projects");
    await expect(
      page.getByRole("heading", { name: /^Projects(?: |$)/ }),
    ).toBeVisible();
    await expect.poll(() => actions.has("dashboard")).toBe(true);
    const cookie = (await context.cookies()).find(
      (cookie) => cookie.name === "cg_session",
    )!;
    expect(cookie.httpOnly).toBe(true);
    expect(cookie.sameSite).toBe("Lax");
    // Even at /login, protected actions enforce authorization themselves.
    expect(
      await (await replay(stranger, actions.get("dashboard")!)).text(),
    ).toContain("UNAUTHENTICATED");
    expect(
      await (await replay(stranger, actions.get("register")!)).text(),
    ).toContain("Setup is complete");
    expect(
      await (
        await replay(stranger, actions.get("registrationOptions")!)
      ).text(),
    ).toContain("already configured");
    await stranger.addCookies([staleCookie!]);
    expect(
      await (await replay(stranger, actions.get("register")!)).text(),
    ).toContain("could not be completed");
    expect(
      (
        await replay(
          context,
          actions.get("dashboard")!,
          undefined,
          "https://evil.example",
        )
      ).status(),
    ).toBe(403);
    expect(
      (
        await replay(context, actions.get("dashboard")!, undefined, null)
      ).status(),
    ).toBe(403);
    expect(
      await (
        await replay(context, actions.get("dashboard")!, '[{"q":123}]')
      ).text(),
    ).toContain("Invalid dashboard filters");
    for (const path of [
      "/api/projects",
      "/api/dashboard",
      "/api/auth/status",
      "/api/issues/1",
    ])
      expect((await context.request.get(base + path)).status()).toBe(404);
    await page.getByRole("button", { name: "Sign out", exact: true }).click();
    await expect(
      page.getByRole("button", { name: "Sign in with passkey" }),
    ).toBeVisible();
    await stranger.addCookies([cookie]);
    expect(
      await (await replay(stranger, actions.get("dashboard")!)).text(),
    ).toContain("UNAUTHENTICATED");
    await stranger.clearCookies();
    forgeOrigin = true;
    await page.getByRole("button", { name: "Sign in with passkey" }).click();
    await expect(page.locator(".error-banner")).toContainText(
      "could not be completed",
    );
    forgeOrigin = false;
    await page.goto(
      base + "/login?next=" + encodeURIComponent("/?view=projects&project=123"),
    );
    await page.getByRole("button", { name: "Sign in with passkey" }).click();
    await expect(page).toHaveURL(base + "/?view=projects&project=123");
    expect(
      await (await replay(context, actions.get("authenticate")!)).text(),
    ).toContain("could not be completed");
    await page.getByRole("link", { name: "Passkeys", exact: true }).click();
    await expect(
      page.getByRole("button", { name: "Remove My laptop" }),
    ).toBeDisabled();
    await expect.poll(() => actions.has("keys")).toBe(true);
    expect(
      await (await replay(stranger, actions.get("keys")!)).text(),
    ).toContain("UNAUTHENTICATED");
    const first = await cdp.send("WebAuthn.getCredentials", {
      authenticatorId,
    });
    await cdp.send("WebAuthn.removeVirtualAuthenticator", { authenticatorId });
    await cdp.send("WebAuthn.addVirtualAuthenticator", { options });
    await page.getByLabel("New passkey name").fill("Backup key");
    await page
      .getByRole("button", { name: "Add passkey", exact: true })
      .click();
    await expect(page.getByRole("status")).toContainText("Passkey added");
    await expect(
      page.getByRole("button", { name: "Remove My laptop" }),
    ).toBeEnabled();
    await page.getByRole("button", { name: "Remove My laptop" }).click();
    await expect(page.getByRole("status")).toContainText("Passkey removed");
    expect(
      await (await replay(stranger, actions.get("remove")!)).text(),
    ).toContain("UNAUTHENTICATED");
    expect(
      await (await replay(context, actions.get("remove")!)).text(),
    ).toContain("last one");
    await page.screenshot({ path: "test-results/passkeys-security.png" });
    const outsiderPage = await stranger.newPage();
    const outsiderCDP = await stranger.newCDPSession(outsiderPage);
    await outsiderCDP.send("WebAuthn.enable");
    const outsider = await outsiderCDP.send(
      "WebAuthn.addVirtualAuthenticator",
      { options },
    );
    for (const credential of first.credentials)
      await outsiderCDP.send("WebAuthn.addCredential", {
        authenticatorId: outsider.authenticatorId,
        credential,
      });
    await outsiderPage.goto(base + "/login");
    await outsiderPage
      .getByRole("button", { name: "Sign in with passkey" })
      .click();
    await expect(outsiderPage.locator(".error-banner")).toContainText(
      "not registered",
    );
    await page.getByRole("button", { name: "Sign out", exact: true }).click();
    await expect(
      page.getByRole("button", { name: "Sign in with passkey" }),
    ).toBeEnabled();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "test-results/passkey-login-mobile.png" });
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth <= window.innerWidth,
      ),
    ).toBe(true);
    await page.getByRole("button", { name: "Sign in with passkey" }).click();
    await expect(
      page.getByRole("heading", { name: /^Issues(?: |$)/ }),
    ).toBeVisible();
    await context.storageState({ path: "test-results/passkey-session.json" });
    const authenticatedHTML = await browser.newContext({
      javaScriptEnabled: false,
      storageState: await context.storageState(),
    });
    const redirected = await authenticatedHTML.newPage();
    await redirected.goto(
      base + "/login?next=" + encodeURIComponent("/?view=projects"),
    );
    await expect(redirected).toHaveURL(base + "/?view=projects");
    await expect(redirected.locator(".auth-card")).toHaveCount(0);
    await authenticatedHTML.close();
    expect(errors).toEqual([]);
    expect(legacyRequests).toEqual([]);
    console.log(
      "PASS: passkey Server Actions, enrollment/race/replay protection, direct action authorization, origin checks, validation, revocation, backup keys, redirects, and no legacy API requests.",
    );
  } finally {
    await browser.close();
  }
}
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
